# Generated by Django 4.0.3 on 2022-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOwner', models.IntegerField()),
                ('docName', models.CharField(max_length=45)),
                ('state', models.BooleanField(default=True)),
                ('content', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Docs_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docs_id', models.IntegerField()),
                ('Users_id', models.CharField(max_length=45)),
                ('state', models.BooleanField(default=True)),
                ('content', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=45)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
