# Generated by Django 4.0.3 on 2022-03-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Docs_Users',
        ),
        migrations.AlterField(
            model_name='docs',
            name='idOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='docsusers',
            name='idDocs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='users.docs'),
        ),
        migrations.AddField(
            model_name='docsusers',
            name='idUsers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.users'),
        ),
    ]
